README.md
For next-error (bound by default to C-x `) to automatically take me to
the location where Kibit was reporting an issue in the *compilation*
buffer, I needed to change the alist it was using to parse the reports
so that they are marked as errors, not just information.
=> Enable emacs' next-error function with kibit hits.

README.md
As suggested in my previous pull request, I have created an Emacs package on melpa.org to host the kibit-related Emacs extensions. This PR changes the README to instruct the reader how to install that package, so it can be installed and updated independently of Kibit itself. Thanks for the great idea and motivation to learn how to contribute to MELPA!
=> Refer to new kibit-helper Emacs package.

src/kibit/driver.clj
When an exception occurs when running a check, output debugging details
about the exception to STDERR.
The Code Climate kitbit engine wraps kibit and emits issues in JSON
for each check on STDOUT. Any unexpected content on STDOUT causes the
engine run to fail as debugging information is expected on STDERR.
This small patch moves the output of debugging information to to
STDERR.
=> Output exception details to STDERR

project.clj
Compiling core.logic 0.8.10 with the latest beta of Clojure 1.9, produces a clojure.spec exception. The problem was fixed by Alex Miller in this commit: https://github.com/clojure/core.logic/commit/29917372ef066c42ca362e3a94f68d620ddd1b56, and core.logic was bumped to 0.8.11 with no other changes.
=> Update core.logic dep to avoid 1.9 spec exception

src/kibit/driver.clj, src/kibit/monkeypatch.clj, test/kibit/test/driver.clj, test/resources/sets.clj
This changeset tweaks the driver implementation to use `Var.setRoot` in a `try/finally` to establish an execution scope with a patched implementation of `tree-term?` that won't allow infinite recursion on sets.
Criticisms of this patch:
1. Blatant monkey patching
2. Assumes that kibit is only ever used via the driver interface, never as a library.
More of an effort could have been made to keep the test impact minimal, but that can be cleaned up.
Fixes #78
=> Monkeypatch core.logic to make sets work

CHANGELOG.md, README.md, project.clj, src/kibit/driver.clj, src/kibit/replace.clj, test/kibit/test/replace.clj
Introduces `--replace` and `--interactive` cli arguments to automatically replace suggestions in source files.
- The performance isn't great in comparison to regular `lein kibit` (about a 5x
slowdown):
```
➜ clojure git:(master)
✗ time lein kibit src/clj/clojure/core.clj > /dev/null lein kibit
src/clj/clojure/core.clj > /dev/null 143.17s user 1.56s system 114% cpu
2:06.60 total ➜ clojure git:(master) ✗ time lein kibit --replace
src/clj/clojure/core.clj > /dev/null lein kibit --replace
src/clj/clojure/core.clj > /dev/null 661.69s user 3.82s system 105% cpu
10:28.20 total ➜ clojure git:(master) ✗ git diff --stat | cat
src/clj/clojure/core.clj | 741 ++++++++++++++++++++++-------------------------
```
Let me know if you notice potential performance issues in this PR
that I missed, but I think …
=> Automatically apply suggestions to source files

.gitignore, kibit/src/kibit/rules/collections.clj, kibit/test/kibit/test/collections.clj
Added rules for [run!](https://clojuredocs.org/clojure.core/run!) so that
```clojure
(doall (map f coll))
```
is replaced by
```clojure
(run! f coll)
```
Got the idea from https://stuartsierra.com/2015/08/25/clojure-donts-lazy-effects
Run is more concise and makes it clear that the iteration produces side-effects
=> Add run! rules

kibit/src/kibit/check.clj, kibit/test/kibit/test/collections.clj
The monkeypatching code was totally appropriate we just weren't using it. Oops.
Fixes #78 for real this time.
=> Actually use the monkeypatches

kibit/project.clj, kibit/src/kibit/check.clj, kibit/src/kibit/check/reader.clj, kibit/test/kibit/test/check_reader.clj, kibit/test/kibit/test/driver.clj, kibit/test/resources/keywords.clj
Fixes #14 
- Takes dependency on clojure.tools.reader 1.0.2, lein deps :tree remains
clean for this project.clj
- Introduces kibit.check.reader namespace for managing all our reading
concerns.
- Migrate reading fns from kibit.check to kibit.check.reader
- Add alias analyzing & util fns to kibit.check.reader
- Add tests for analyzing fns to kibit.check-reader
- Add keywords.clj test resource which includes several iterations of
alias backflips to make sure that some simple edge cases for
keyword reading are handled.
Notes:
I tested this across our internal projects which we want to integrate kibit into our CI process on, where we use a lot of namespace aliased keywords (largely due to spec)
We had previously had a blind spot past any aliased keyword in any file, so using this branch …
=> Migrate to tools.reader to solve aliased keyword pains

kibit/src/kibit/check.clj, kibit/test/kibit/test/reporters.clj
- driver/run was returning simplify maps without :file component present in map. Because of that  results from driver/run were not enough informative from perspective of kibit consumers.
- all tests are passing on win. They were not passing because of println and newline producing \r\n on win while on Linux it is just \n
=> Fixed issues: #207 unit tests fails on win due to line breaks, #206 driver/run returns simplify maps with no :file

README.md
As for vim kibit integration:
Originally, there is already one. [kibit-vim](https://github.com/fbeline/kibit-vim)
kibit-vim is invoked by kibit leiningen plugin.
I wrote a new one. [vim-kibit](https://github.com/humorless/vim-kibit)
vim-kibit is invoked by vim-fireplace session.
By suggestion of issue #209, I send this PR.
=> issue #209: add usage from vim to README.md

kibit/src/kibit/driver.clj
Hi,
I've added a file name into an error message and I think it'd be helpful.
=> Added a file path into an error message while reading a file fixes #405

lein-kibit/src/leiningen/kibit.clj
This fixes kibit usage when :repositories ^:replace is used in the original project.clj.
Fixes #201
=> Use :repositories from original project in synthetic project.clj

kibit/src/kibit/check/reader.clj, kibit/test/kibit/test/check_reader.clj
This pull request updates the check reader to address https://github.com/jonase/kibit/issues/202.
As noted in the comments, I used [clojure.tools.namespace.parse][1] as
a basis for recovering dependencies, and added a way to collect the
alias values. Created the `derive-aliases-from-deps` function to
create the alias-map format, and then updated `derive-aliases`
implementations to use it.
[1]: https://github.com/clojure/tools.namespace
=> Implement a solution for Issue #202

README.md, kibit/src/kibit/monkeypatch.clj, kibit/src/kibit/rules.clj, kibit/test/kibit/test/replace.clj
1) ‘defn-‘ replaces ‘defn ^:pivate’ (<- function in question not called from any other namespace)
2) ‘unification’ replaces ‘unfication’
3) ‘what was written’ replaces ‘was was written’
4) ‘its’ replaces ‘it’s’ in possessive usage
I say unambiguous, but of course there's always multiple perspectives. Easy to break apart or change
Opted for single commit because these changes would be easy to move somewhere else and personally am averse to making commits as small as the ones for making each change individually would be. 
Could certainly see a case for rolling the `defn` change seperately from the doc changes though.
=> Fix unambiguous misrenderings

kibit/src/kibit/driver.clj, kibit/src/kibit/replace.clj
From the commits:
_'Rules'->'rules' in docstring mid-sentence_
Might recommend further changing to `rules` and its ilk throughout
docstring and codebase to conform with style guide for docstring params.
_'replace in'->'replace' for expr replacement_
It is my fallible understanding that for `kibit.replace/replace-expr`,
the return value is the entire expression.
Leaving aside the discussion that `replace-file` might perhaps be more
optimally rendered as `replace-file!`—and `replace-expr` as
`convert-expr` or similar—what seems clear is that the entire
expression is being operated on and returned.
The replacement operation is not being done only in part. Therefore
terminal preposition `in` misses the mark
=> Docstring fixes

kibit/deps.edn, kibit/src/kibit/driver.clj
I'm playing around with graalvm to compile a native version of kibit. This is needed to make it happy.
I added a deps.edn so that kibit can be used in another project's deps.edn via :local/root. If a new release is in the works, this could easily be omitted.
=> Add (more) type hints.

kibit/src/kibit/check.clj
I'm writing an editor plugin that will allow replacing of Kibit suggestions as you type, one by one. In order to do that, I need to tell the editor what range (start line/col to end line/col) can be replaced. Kibit internally has that information, but not in a way that I can access it from the API (unless I missed something of course). 
This pull request exposes the `:end-line` and `:end-column` meta so that I can use it in my editor plugin.
(Note that I'm suing `identity` as a reporter so that I get the data structure for further processing in my plugin.)
I would be super-greatful if this can be merged and deployed, so that I don't have to publish my own fork of Kibit, which I'd rather avoid. Many thanks!
=> Allows tools to also use the end of a range besides just the start

kibit/src/kibit/check/reader.clj
This is a minor enhancement that fixes: #242
=> Kibit cannot parse ns with string requires

README.md
=> docs: add deps.edn alias to readme

project.clj
`lein-marginalia` has been unused since added. (Can't even be used until it's moved to `:plugins`.)
I read each of the dependency's change logs and perused the code changes. Nothing stood out but I prefer to stay up to date even when there are minimal needed changes.
=> Update dependencies to latest, remove unused lein-marginalia
